// angular-client/src/app/components/dashboard/customer-segments-chart/customer-segments-chart.component.ts
import { Component, ElementRef, Input, OnChanges, OnDestroy, SimpleChanges, ViewChild, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import Chart from 'chart.js/auto';

interface CustomerSegment {
  id: number;
  segmentName: string;
  percentage: string | number;
}

@Component({
  selector: 'app-customer-segments-chart',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './customer-segments-chart.component.html',
  styleUrls: ['./customer-segments-chart.component.scss']
})
export class CustomerSegmentsChartComponent implements OnChanges, OnDestroy, AfterViewInit {
  @Input() data: CustomerSegment[] = [];
  @ViewChild('chartCanvas') chartCanvas!: ElementRef<HTMLCanvasElement>;
  
  chartInstance: Chart | null = null;

  ngAfterViewInit() {
    this.createChart();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['data'] && this.chartCanvas) {
      this.createChart();
    }
  }

  ngOnDestroy() {
    if (this.chartInstance) {
      this.chartInstance.destroy();
    }
  }

  private createChart() {
    if (!this.chartCanvas || !this.data || this.data.length === 0) return;

    if (this.chartInstance) {
      this.chartInstance.destroy();
    }

    const ctx = this.chartCanvas.nativeElement.getContext('2d');
    if (!ctx) return;

    const labels = this.data.map(segment => segment.segmentName);
    const percentages = this.data.map(segment => {
      return typeof segment.percentage === 'string' 
        ? parseFloat(segment.percentage) 
        : segment.percentage;
    });

    this.chartInstance = new Chart(ctx, {
      type: 'doughnut',
      data: {
        labels: labels,
        datasets: [{
          data: percentages,
          backgroundColor: [
            '#2448a5',  // Blue
            '#C6DBFC',  // Light Blue
            '#7b7b7b',  // Gray
            '#90CAF9'   // Another shade of blue
          ],
          borderWidth: 0,
          hoverOffset: 4
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            position: 'bottom',
            labels: {
              padding: 15,
              usePointStyle: true,
              pointStyle: 'rectRounded',
            }
          },
          tooltip: {
            callbacks: {
              label: (context) => {
                const label = context.label || '';
                const value = context.raw;
                return `${label}: ${value}%`;
              }
            }
          }
        },
        cutout: '65%'
      }
    });
  }
}
<div class="chart-container">
  <div class="chart-title">Customer Segments</div>
  <canvas #chartCanvas></canvas>
</div>

// client/src/components/dashboard/customer-segments-chart.tsx
import React, { useEffect, useRef } from 'react';
import Chart from 'chart.js/auto';

interface CustomerSegment {
  id: number;
  segmentName: string;
  percentage: string | number;
}

interface CustomerSegmentsChartProps {
  data: CustomerSegment[];
}

const CustomerSegmentsChart: React.FC<CustomerSegmentsChartProps> = ({ data }) => {
  const chartRef = useRef<HTMLCanvasElement>(null);
  const chartInstance = useRef<Chart | null>(null);

  useEffect(() => {
    if (!chartRef.current || !data || data.length === 0) return;

    // Destroy previous chart if it exists
    if (chartInstance.current) {
      chartInstance.current.destroy();
    }

    const ctx = chartRef.current.getContext('2d');
    if (!ctx) return;

    const labels = data.map(segment => segment.segmentName);
    const percentages = data.map(segment => {
      // Convert percentage to number if it's a string
      return typeof segment.percentage === 'string' 
        ? parseFloat(segment.percentage) 
        : segment.percentage;
    });

    chartInstance.current = new Chart(ctx, {
      type: 'doughnut',
      data: {
        labels: labels,
        datasets: [{
          data: percentages,
          backgroundColor: [
            '#2448a5',  // Blue
            '#C6DBFC',  // Light Blue
            '#7b7b7b',  // Gray
            '#90CAF9'   // Another shade of blue
          ],
          borderWidth: 0,
          hoverOffset: 4
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            position: 'bottom',
            labels: {
              padding: 15,
              usePointStyle: true,
              pointStyle: 'rectRounded',
              pointStyleWidth: 16 // Maintain rectangular style for color indicators
            }
          },
          tooltip: {
            callbacks: {
              label: (context) => {
                const label = context.label || '';
                const value = context.raw;
                return `${label}: ${value}%`;
              }
            }
          }
        },
        cutout: '65%'
      }
    });

    return () => {
      if (chartInstance.current) {
        chartInstance.current.destroy();
      }
    };
  }, [data]);

  return (
    <div>
      <h2 className="text-lg font-semibold text-gray-900 mb-4">Customer Segments</h2>
      <div className="h-60">
        <canvas ref={chartRef}></canvas>
      </div>
    </div>
  );
};

export default CustomerSegmentsChart;
